server:
  port: 8080

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka:8761/eureka/

order-service:
  ribbon:
    ConnectionTimeout: 500
    ReadTimeout: 5000

product-service:
  ribbon:
    ConnectionTimeout: 500
    ReadTimeout: 5000

feign:
    hystrix:
      enabled: true
