version: '2.1'

services:
  eureka:
    build: ./spring-cloud-eureka
    mem_limit: 350m
    ports:
      - "8761:8761"

  order-service:
    build:
      context: ./order-service
    mem_limit: 350m
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    depends_on:
      eureka:
        condition: service_started


  product-service:
    build:
      context: ./product-service
    mem_limit: 350m
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    depends_on:
      eureka:
        condition: service_started

  front-api-client:
    build:
      context: ./front-api-client
    mem_limit: 350m
    ports:
      - "3000:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    depends_on:
      eureka:
        condition: service_started